# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

project_name: zyrocli

before:
  hooks:
    - go mod tidy

builds:
  - id: zyrocli
    main: ./cmd/zyrocli
    binary: zyrocli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: zyrocli
    formats: ["tar.gz"]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'
  algorithm: sha256

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
  groups:
    - title: '🚀 Features'
      regexp: '^.*feat[(\\w)]*:+.*$'
      order: 0
    - title: '🐛 Bug fixes'
      regexp: '^.*fix[(\\w)]*:+.*$'
      order: 1
    - title: '🧰 Maintenance'
      order: 2

